### PR TITLE
Validate that locals do not include dots. Fixes #36

### LINKED ISSUE #36: Dots in GMail addresses
Hi, 
what do you think about extending your library in order to also support validating email addresses which only differ in moveable/number of dots in the account name?
http://www.makeuseof.com/tag/1-awesome-gmail-tip-you-dont-know-about-seriously/

The domain names (gmail.com, googlemail.com, ...) to check against could be stored in an additional yaml file.
The question is: Would this work without having to store the "raw" (i.e. without any dots at all) version of the account part of the email address in an additional database column?

Thanks for considering this and great work btw.
Greets
valley

### PR DESCRIPTION
**Pull request by pjmartorell**
- Resolves #36
- Add `disallow_dotted` option to enable validation of locals with dots
- Add `dotted?` method to check if a local includes a dot

### CODE REVIEW

**Comment by FireFart** [comment]
Shouldn't we add this case to `subaddressed?` too?

**Comment by pjmartorell** [comment]
@FireFart having it in a separate option allows more flexibility and does not create a breaking change with the current behavior

**Comment by micke** [comment]
Thanks @pjmartorell 
I was under the impression that if you register a gmail address with a dot in it, that you don't get the undotted version too.

**Comment by micke** [comment]
I just pushed version 3.2.0 to rubygems!

**Comment by pjmartorell** [comment]
thanks, @micke!

**Pull request merged**
