### PR TITLE
Use sets for faster lookups

### PR DESCRIPTION
**Pull request by corny**

### CODE REVIEW

**Comment by micke** [comment]
Hi, thanks for your contribution!
Do you have any benchmarks on the performance benefits?

**Comment by dmke** [comment]
`Array#includes?` makes N string comparisons, `Hash#key?` (what `Set` uses internally) is (almost) constant (O(n) vs. O(1)).

This benchmark contructs a list with 15k entries (like your email list), adds a needle (propably somewhere in the first 1/3 of the list) and tries to lookup that needle as often as possible. Depending on the state of your random generator, this yields a performance improvement in the range of **3 orders of magnitude.**

<details><summary>code</summary>

```ruby
require "benchmark/ips"

NEEDLE = "example.com"

LIST = begin
  list = Array.new(15000) { SecureRandom.urlsafe_base64(16) }
  list << NEEDLE
  list.sort.uniq
end

SET = Set.new(LIST)

Benchmark.ips do |x|
  x.report("Array#include?") {|n|
    i = 0
    while i < n
      raise unless LIST.include?(NEEDLE)
      i += 1
    end
  }
  x.report("Set#include?") {|n|
    i = 0
    while i < n
      raise unless SET.include?(NEEDLE)
      i += 1
    end
  }
  x.compare!
end
```

</details>

<details><summary>benchmark results</summary>

```console
$ ruby bench.rb
Warming up --------------------------------------
      Array#include?     1.030k i/100ms
        Set#include?   447.997k i/100ms
Calculating -------------------------------------
      Array#include?     10.570k (± 1.8%) i/s -     53.560k in   5.068737s
        Set#include?     12.338M (± 1.5%) i/s -     61.824M in   5.011884s

Comparison:
        Set#include?: 12338072.3 i/s
      Array#include?:    10570.1 i/s - 1167.26x  slower
```

</details>

**Comment by dmke** [comment]
Here's another benchmark comparing the lookup method changed in this PR:

<details><summary>code</summary>

```ruby
#!/usr/bin/env ruby

require "set"
require "securerandom"
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "benchmark-ips"
end

NEEDLE = "example.com"

LIST = begin
  list = Array.new(15000) { SecureRandom.urlsafe_base64(16) }
  list << NEEDLE
  list.sort.uniq
end

SET = Set.new(LIST)

def lookup_with_re(list)
  needle = "mail.#{NEEDLE}"
  list.any? {|el|
    el.end_with?(NEEDLE) && needle =~ /\A(?:.+\.)*?#{el}/
  }
end

def lookup_without_re(list)
  needle = "mail.#{NEEDLE}"
  return true if list.include?(needle)
  return false unless i = needle.index(".")
  list.include? needle[(i+1)..-1]
end

Benchmark.ips do |x|
  x.report("Array w/ RE")  { raise unless lookup_with_re(LIST) }
  x.report("Array w/o RE") { raise unless lookup_without_re(LIST) }
  x.report("Set w/ RE")    { raise unless lookup_with_re(SET) }
  x.report("Set w/o RE")   { raise unless lookup_without_re(SET) }

  x.compare!
end
```

</details>


<details><summary>results</summary>

```console
% ruby bench.rb
Warming up --------------------------------------
         Array w/ RE   117.000  i/100ms
        Array w/o RE   423.000  i/100ms
           Set w/ RE   100.000  i/100ms
          Set w/o RE   136.312k i/100ms
Calculating -------------------------------------
         Array w/ RE      1.214k (± 2.0%) i/s -      6.084k in   5.015103s
        Array w/o RE      4.253k (± 1.3%) i/s -     21.573k in   5.072693s
           Set w/ RE      1.004k (± 1.4%) i/s -      5.100k in   5.082329s
          Set w/o RE      1.846M (± 1.2%) i/s -      9.269M in   5.022063s

Comparison:
          Set w/o RE:  1845988.2 i/s
        Array w/o RE:     4253.5 i/s - 433.99x  slower
         Array w/ RE:     1213.6 i/s - 1521.05x  slower
           Set w/ RE:     1003.7 i/s - 1839.23x  slower
```

</details>

By removing the RE in the lookup loop, the performance increases 3½-fold (1200 vs. 4200 iterations/sec). Using `Set` instead of `Array` gains another factor of 500.

**Comment by micke** [comment]
Thank you @corny for your contributions and @dmke for taking the time and constructing the benchmarks!

I've never used the gem in a project where the performance was an issue!
I'm going to cut a release right away

**Comment by micke** [comment]
I Just pushed version `v3.1.0` to rubygems.org
Thanks a bunch!

**Comment by corny** [comment]
@dmke Thanks a lot for your beautiful benchmarks!

**Comment by corny** [comment]
@micke Are you serious? Your change in c92c566e759113ad1c43a8c7824b9d38be3138ea makes the performance as bad as before again.

**Pull request merged**
