### PR TITLE
remove cock.li addresses

### PR DESCRIPTION
**Pull request by tuptuptuu**
cock.li is a legitimate email provider which does not offer disposable addresses.

### CODE REVIEW

**Comment by erkanercan** [comment]
I don't think this is a appropriate pr.

**Comment by tuptuptuu** [comment]
> I don't think this is a appropriate pr.

Why do you think that?

**Comment by micke** [comment]
Thanks for your PR but we won't be merging this as the host in question is used for illicit purposes.

**Comment by tuptuptuu** [comment]
> Thanks for your PR but we won't be merging this as the host in question is used for illicit purposes.

What does "illicit purposes" mean here?

**Pull request closed without merging**
